server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
    password: root@123
  application:
    name: User
  mail:
    host: smtp.gmail.com
    port: 587
    username: siranish97@gmail.com
    password: ltyyuekygrophyju
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mail:
  attachment: /Users/anishsrivastava/Desktop/Resume/ANISH_UPDATED_2.pdf

Email:
  list: siranish97@gmail.com




